services:
  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.format=json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db_migration:
    image: django:latest
    command: python manage.py migrate
    volumes:
      - ./rds-combined-ca-bundle.pem:/certs/rds-combined-ca-bundle.pem
    env_file:
      - .env

  backend:
    image: django:latest
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./rds-combined-ca-bundle.pem:/certs/rds-combined-ca-bundle.pem
    depends_on:
      - db_migration
      - redis
    command: gunicorn -w 4 -b 0.0.0.0:8000 config.wsgi:application --timeout 120 --log-level info
    labels:
      - traefik.enable=true
      # Router - matches /api, /admin, and /webhook paths
      - traefik.http.routers.backend.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/webhook`))
      - traefik.http.routers.backend.entrypoints=web,websecure
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=mytlschallenge
      - traefik.http.routers.backend.middlewares=backend-headers@docker
      - traefik.http.routers.backend.priority=10

      # Service
      - traefik.http.services.backend.loadbalancer.server.port=8000

      # Middleware (headers)
      - traefik.http.middlewares.backend-headers.headers.SSLRedirect=true
      - traefik.http.middlewares.backend-headers.headers.STSSeconds=31536000
      - traefik.http.middlewares.backend-headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.backend-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.backend-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.backend-headers.headers.SSLHost=${WEB_SUBDOMAIN}.${DOMAIN_NAME}
      - traefik.http.middlewares.backend-headers.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.backend-headers.headers.STSPreload=true
    restart: unless-stopped

  flower:
    image: django:latest
    container_name: flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./rds-combined-ca-bundle.pem:/certs/rds-combined-ca-bundle.pem
    depends_on:
      - db_migration
      - redis
    command: celery -A config.extensions flower --basic-auth=${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}
    labels:
      - traefik.enable=true

      # Router
      - traefik.http.routers.flower.rule=Host(`${FLOWER_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.flower.entrypoints=websecure
      - traefik.http.routers.flower.tls=true
      - traefik.http.routers.flower.tls.certresolver=mytlschallenge
      - traefik.http.routers.flower.middlewares=flower-headers@docker

      # Middleware (headers)
      - traefik.http.middlewares.flower-headers.headers.SSLRedirect=true
      - traefik.http.middlewares.flower-headers.headers.STSSeconds=315360000
      - traefik.http.middlewares.flower-headers.headers.browserXSSFilter=true
      - traefik.http.middlewares.flower-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.flower-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.flower-headers.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.flower-headers.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.flower-headers.headers.STSPreload=true

    restart: unless-stopped

  celery_worker:
    image: django:latest
    container_name: celery_worker
    env_file:
      - .env
    volumes:
      - ./rds-combined-ca-bundle.pem:/certs/rds-combined-ca-bundle.pem
    depends_on:
      - db_migration
      - redis
    command: celery -A config.extensions worker --loglevel=info -Q n8n --concurrency=10
    healthcheck:
      test: ["CMD", "celery", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  celery_beat:
    image: django:latest
    container_name: celery_beat
    env_file:
      - .env
    volumes:
      - ./rds-combined-ca-bundle.pem:/certs/rds-combined-ca-bundle.pem
    depends_on:
      - db_migration
      - redis
    command: celery -A config.extensions beat --loglevel=info
    healthcheck:
      test: ["CMD", "celery", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  n8n_data:
  traefik_data:
  redis_data:
